name = "bytesized"
type = "javascript"
account_id = "dc56444c4c955a1653106ccf997c1067"
workers_dev = true

[env.production]
workers_dev = false
zone_id = "8277f61d090cd9092908ea8e81f30ffd"
route = "https://www.bytesized.xyz/*"

[site]
bucket = "./public"
entry-point = "workers-site"
