on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@master
      - name: Cache .cache folder
        uses: actions/cache@master
        env:
          cache-name: cache-bytesized-public
        with:
          key: ${{ runner.os }}-cache
          path: ${{ github.workspace }}/.cache
      - name: Cache public folder
        uses: actions/cache@master
        env:
          cache-name: cache-bytesized-public
        with:
          key: ${{ runner.os }}-public
          path: ${{ github.workspace }}/public
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: NPM ci
        run: 'npm ci'
      - name: Build app
        run: 'npm run gatsby:build:incremental'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
