on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: "[var] Yarn cache directory"
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "[cache] .cache"
        uses: actions/cache@master
        with:
          key: gatsby-cache-folder
          path: .cache
      - name: "[cache] public"
        uses: actions/cache@master
        with:
          key: gatsby-public-folder
          path: public
      - name: "[cache] workers-site/dist/worker.js"
        uses: actions/cache@master
        with:
          key: ${{ runner.os }}-workers-site-dist-${{ hashFiles('**/worker.js') }}
          path: workers-site/dist/worker.js
      - name: "[cache] yarn cache"
        uses: actions/cache@master
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "[cache] node_modules"
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn run build'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
