on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: NPM install
        run: 'npm install'
      - name: Build app
        run: 'npm run build'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
      - name: Publish app
        uses: signalnerve/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.apiToken }}
          environment: 'production'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.discordWebhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'bytesized.xyz has been deployed.'
