on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: "[var] Yarn cache directory"
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "[cache] .cache"
        uses: actions/cache@master
        with:
          key: gatsby-cache-folder
          path: .cache
      - name: "[cache] public"
        uses: actions/cache@master
        with:
          key: gatsby-public-folder
          path: public
      - name: "[cache] workers-site/dist/worker.js"
        uses: actions/cache@master
        with:
          key: ${{ runner.os }}-workers-site-dist-${{ hashFiles('**/worker.js') }}
          path: workers-site/dist/worker.js
      - name: "[cache] yarn cache"
        uses: actions/cache@master
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "[cache] node_modules"
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: "[cache] workers-site node_modules"
        uses: actions/cache@master
        with:
          path: workers-site/node_modules
          key: ${{ runner.os }}-workkers-site-node_modules-${{ hashFiles('**/workers-site/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-workers-site-node_modules-
      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn run build'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
      - name: "[ci] Publish with Cloudflare Workers"
        uses: cloudflare/wrangler-action@master
        with:
          apiToken: ${{ secrets.apiToken }}
          environment: 'production'
