on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: NPM install
        run: 'npm install'
      - name: Build app
        run: 'npm run gatsby:build:incremental'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
      - name: Publish app
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.apiToken }}
          environment: 'production'
