on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Gatsby Cache Folder
        uses: actions/cache@master
        with:
          key: gatsby-cache-folder
          path: .cache
      - name: Gatsby Public Folder
        uses: actions/cache@master
        with:
          key: gatsby-public-folder
          path: public
      - name: Yarn cache
        uses: actions/cache@master
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn install
        run: 'yarn install --pure-lockfile'
      - name: Build app
        run: 'yarn run gatsby:build:incremental'
        env:
          SANITY_READ_TOKEN: ${{ secrets.sanityReadToken }}
      - name: Publish app
        uses: cloudflare/wrangler-action@0e28281
        with:
          apiToken: ${{ secrets.apiToken }}
          environment: 'production'
